AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  DisabledByDefault: true
  NewCops: enable
  Exclude:
    - railseventstore.org/**/*
    - contrib/**/*
    - "**/generators/templates/**/*"
    - "**/bin/*"
    - "**/*_spec.rb"
    - "**/*_test.rb"
    - "**/*_lint.rb"

Lint:
  Enabled: true

Lint/SuppressedException:
  Enabled: false